### PR TITLE
Compress HTML in Liquid

### PR DESCRIPTION
**Pull request by doktorbro**
There is a way to [compress HTML](https://github.com/penibelst/jekyll-compress-html) on Github Pages. I’m curious what you think about my Liquid based solution.

### CODE REVIEW

**Comment by kangax** [comment]
Looks interesting. Not sure it's super important to compress my blog but I'm sure it could come in useful in other places.

**Comment by doktorbro** [comment]
Compressing your blog would be a statement from the creator of HTML minifier.

What are places HTML compression is useful? Can you please list some live examples that use your JS based minifier? I would like to add a list of target groups to my readme.

**Comment by kangax** [comment]
> Compressing your blog would be a statement from the creator of HTML minifier.

Well, my statement is to use the right tool for the right job ;) When I published html minifier, I mentioned that this is a very niche optimization. It's useful in places with tons of content (documentation, specification, catalogs, etc.)

**Comment by kangax** [comment]
Your plugin looks useful but I'd need to check that everything works fine before making this live and I unfortunately don't have time for this now.

**Pull request closed without merging**
